# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : "Caleb Cooper"
title_separator          : "-"
name                     : &name "Caleb Cooper"
description              : &description "Personal page and portfolio of Caleb Cooper, focused on neuroscience, research, and community mentorship."
url                      : https://cbcoop.github.io
baseurl                  : "" # the subpath of your site
repository               : "cbcoop/cbcoop.github.io"
teaser                   : "500x300.png" # Replace with your custom teaser image
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : false
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  path                   : # blank (default) uses feed.xml

# SEO Related
google_site_verification : "your-google-site-verification-code"
bing_site_verification   : "your-bing-site-verification-code"

# Social Sharing
twitter:
  username               : "cbcoop"
facebook:
  username               :
og_image                 : "500x300.png" # Your social sharing image

# Analytics
analytics:
  provider               :  "google-universal"
  google:
    tracking_id          : "UA-XXXXXXXXX-X"

# Site Author
author:
  name             : "Caleb Cooper"
  avatar           : "caleb-avatar.jpg"
  bio              : "Caleb Cooper is passionate about neuroscience, mentorship, and making a difference in his community."
  location         : "Mississippi, USA"
  employer         : "Tougaloo College, Jackson State University"
  googlescholar    : "https://scholar.google.com/citations?user=your-google-scholar-id"
  email            : "cbcoop@tougaloo.edu"
  github           : "cbcoop"
  linkedin         : "https://www.linkedin.com/in/caleb-cooper"
  orcid            : "http://orcid.org/0000-0002-8471-5569"
  twitter          : "cbcoop"
  researchgate     : "https://www.researchgate.net/profile/Caleb-Cooper"
  impactstory      : "https://profiles.impactstory.org/u/caleb-cooper"

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor

# Outputting
permalink: /:categories/:title/
timezone: America/Chicago

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
